language: android

jdk:
  - oraclejdk8

#addons:
#  apt:
#    sources:
#    - avsm
#    packages:
#    - autoconf
#    - automake
#    - build-essential
#    - libffi-dev
#    - libgmp-dev
#    - libmpc-dev
#    - libmpfr-dev
#    - m4
#    - pkg-config
#    - python-software-properties
#    - unzip
#    - zlib1g-dev
#    - ocaml
#    - ocaml-native-compilers
#    - camlp4-extra opam

before_install:
#  - source .build-scripts/install-infer.sh
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean build --no-daemon

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
